export const LINE_NAME = {
  6: "Lão âm (động)",
  7: "Thiếu dương",
  8: "Thiếu âm",
  9: "Lão dương (động)",
};

export const TRIGRAM = {
  0b111: { name: "Càn", symbol: "☰", element: "Trời" },
  0b000: { name: "Khôn", symbol: "☷", element: "Đất" },
  0b001: { name: "Chấn", symbol: "☳", element: "Sấm" },
  0b110: { name: "Tốn", symbol: "☴", element: "Gió" },
  0b010: { name: "Khảm", symbol: "☵", element: "Nước" },
  0b101: { name: "Ly", symbol: "☲", element: "Lửa" },
  0b100: { name: "Cấn", symbol: "☶", element: "Núi" },
  0b011: { name: "Đoài", symbol: "☱", element: "Đầm" },
};

// (thượng, hạ) -> [số quẻ, tên, ý nghĩa ngắn]
export const HEXAGRAMS = {
  "7,7": [1, "Thuần Càn", "Sáng tạo, cương kiện, năng động"],
  "0,0": [2, "Thuần Khôn", "Bao dung, nhu thuận, tiếp nhận"],
  "2,1": [3, "Thủy Lôi Truân", "Khởi đầu gian nan, cần kiên trì"],
  "4,2": [4, "Sơn Thủy Mông", "Khai sáng tuổi trẻ, học hỏi"],
  "2,7": [5, "Thủy Thiên Nhu", "Kiên nhẫn chờ thời cơ"],
  "7,2": [6, "Thiên Thủy Tụng", "Tranh chấp, kiện cáo"],
  "0,2": [7, "Địa Thủy Sư", "Quân đội, tổ chức kỷ luật"],
  "2,0": [8, "Thủy Địa Tỷ", "Hòa hợp, thân cận"],
  "6,7": [9, "Phong Thiên Tiểu Súc", "Tích lũy nhỏ, kiềm chế nhẹ"],
  "7,3": [10, "Thiên Trạch Lý", "Bước đi cẩn trọng"],
  "0,7": [11, "Địa Thiên Thái", "Hanh thông, thái bình"],
  "7,0": [12, "Thiên Địa Bĩ", "Bế tắc, ngăn cách"],
  "7,5": [13, "Thiên Hỏa Đồng Nhân", "Đồng tâm hiệp lực"],
  "5,7": [14, "Hỏa Thiên Đại Hữu", "Sở hữu lớn, thịnh vượng"],
  "0,4": [15, "Địa Sơn Khiêm", "Khiêm tốn, nhún nhường"],
  "1,0": [16, "Lôi Địa Dự", "Hứng khởi, vui mừng"],
  "3,1": [17, "Trạch Lôi Tùy", "Tùy thuận hoàn cảnh"],
  "4,6": [18, "Sơn Phong Cổ", "Sửa chữa đổ nát"],
  "0,3": [19, "Địa Trạch Lâm", "Đến gần, giáng lâm"],
  "6,0": [20, "Phong Địa Quán", "Quan sát, chiêm ngưỡng"],
  "5,1": [21, "Hỏa Lôi Phệ Hạp", "Phá vỡ trở ngại"],
  "4,5": [22, "Sơn Hỏa Bí", "Vẻ đẹp, trang sức"],
  "4,0": [23, "Sơn Địa Bác", "Bóc lột, suy tàn"],
  "0,1": [24, "Địa Lôi Phục", "Trở lại, hồi phục"],
  "7,1": [25, "Thiên Lôi Vô Vọng", "Không vọng tưởng, chân thật"],
  "4,7": [26, "Sơn Thiên Đại Súc", "Tích lũy lớn"],
  "4,1": [27, "Sơn Lôi Di", "Nuôi dưỡng, dưỡng sinh"],
  "3,6": [28, "Trạch Phong Đại Quá", "Vượt mức, quá độ"],
  "2,2": [29, "Thuần Khảm", "Hiểm trong hiểm"],
  "5,5": [30, "Thuần Ly", "Sáng tỏ, rực rỡ"],
  "3,4": [31, "Trạch Sơn Hàm", "Cảm ứng, tương giao"],
  "1,6": [32, "Lôi Phong Hằng", "Bền lâu, kiên định"],
  "7,4": [33, "Thiên Sơn Độn", "Rút lui khéo léo"],
  "1,7": [34, "Lôi Thiên Đại Tráng", "Cường thịnh, mạnh mẽ"],
  "5,0": [35, "Hỏa Địa Tấn", "Tiến lên, thăng tiến"],
  "0,5": [36, "Địa Hỏa Minh Di", "Ánh sáng bị che lấp"],
  "6,5": [37, "Phong Hỏa Gia Nhân", "Gia đình hòa thuận"],
  "5,3": [38, "Hỏa Trạch Khuê", "Chia rẽ, đối lập"],
  "2,4": [39, "Thủy Sơn Kiển", "Gian nan, trở ngại"],
  "1,2": [40, "Lôi Thủy Giải", "Giải tỏa, hóa giải"],
  "4,3": [41, "Sơn Trạch Tổn", "Giảm bớt, hy sinh"],
  "6,1": [42, "Phong Lôi Ích", "Tăng thêm, lợi ích"],
  "3,7": [43, "Trạch Thiên Quải", "Quyết đoán, dứt khoát"],
  "7,6": [44, "Thiên Phong Cấu", "Gặp gỡ bất ngờ"],
  "3,0": [45, "Trạch Địa Tụy", "Tụ hội, đoàn kết"],
  "0,6": [46, "Địa Phong Thăng", "Vươn lên, thăng hoa"],
  "3,2": [47, "Trạch Thủy Khốn", "Khốn cùng, bế tắc"],
  "2,6": [48, "Thủy Phong Tỉnh", "Giếng nước, nguồn nuôi"],
  "3,5": [49, "Trạch Hỏa Cách", "Cách mạng, thay đổi"],
  "5,6": [50, "Hỏa Phong Đỉnh", "Đổi mới, ổn định"],
  "1,1": [51, "Thuần Chấn", "Chấn động, sấm sét"],
  "4,4": [52, "Thuần Cấn", "Dừng lại, tĩnh chỉ"],
  "6,4": [53, "Phong Sơn Tiệm", "Tiến dần, từ từ"],
  "1,3": [54, "Lôi Trạch Quy Muội", "Gả em gái, vị trí lệch"],
  "1,5": [55, "Lôi Hỏa Phong", "Phong phú, đỉnh thịnh"],
  "5,4": [56, "Hỏa Sơn Lữ", "Lữ khách, lang thang"],
  "6,6": [57, "Thuần Tốn", "Thuận theo, mềm dẻo"],
  "3,3": [58, "Thuần Đoài", "Vui vẻ, hòa duyệt"],
  "6,2": [59, "Phong Thủy Hoán", "Phân tán, lan tỏa"],
  "2,3": [60, "Thủy Trạch Tiết", "Tiết chế, điều độ"],
  "6,3": [61, "Phong Trạch Trung Phu", "Trung tín bên trong"],
  "1,4": [62, "Lôi Sơn Tiểu Quá", "Vượt nhỏ, lệch nhẹ"],
  "2,5": [63, "Thủy Hỏa Ký Tế", "Đã thành, hoàn tất"],
  "5,2": [64, "Hỏa Thủy Vị Tế", "Chưa thành, dang dở"],
};
